name: Vatren Jurin
favicon: null
layout_spectrum: 0.24357
typography_spectrum: 0.7987608537077904
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0.835410384228453
  saturation: 0.5074440971948206
  rhythmicContrast: 0.75
purpose: []
